### ISSUE TITLE
Please add circuit diagram to the repo

### ISSUE THREAD

**Issue by moshfeu** [urish/tiny-simon#1]
A [tinkercad](https://www.tinkercad.com) will be BEST.

Thanks!

**Comment by urish** [comment]
Wow, that was quick :)

**Comment by moshfeu** [comment]
Thanks for github feed :)
It catched my eyes because I started to implement it with my sun but I saw it's harder so we moved to Scratch. It's going well for now.

**Comment by urish** [comment]
Here we go: https://www.tinkercad.com/things/iCJghfJcX68-tiny-simon-says

For some reason, the speaker is not working - if you figure it out, please let me know

**Comment by moshfeu** [comment]
It's very working for me.

**Comment by urish** [comment]
Yes, I figured out yesterday that `tone()` doesn't work on ATTiny85, so I implemented my own `beep()` routine

**Comment by moshfeu** [comment]
Sounds good :)
